FROM python:3.11-slim-buster

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ENV HOME=/app
WORKDIR $HOME
RUN mkdir $HOME/app

# install system dependencies
RUN apt-get update \
  && apt-get -y install netcat gcc postgresql \
  && apt-get clean

RUN pip install --trusted-host pypi.python.org --upgrade pip

COPY requirements.dev.txt $HOME/requirements.txt
RUN pip install --trusted-host pypi.python.org  -r requirements.txt

COPY ./app $HOME/app